### ISSUE TITLE
Don't generate fake component files when IDEA starts supporting full web-types spec.

### ISSUE THREAD

**Issue by panstromek** [panstromek/quasar-ide-helper#17]
JetBrains is working on official support of Vue component libraries through `web-types` helper file. Quasar already generates it since [this PR](https://github.com/quasarframework/quasar/pull/4749), but IDEA still can't read/use all information from it. Once it does, it will be way more powerfull than our hacking technique used in `ide-helper`.

Here is a checklist for what's still missing natively in idea and is provided by ide-helper.  When this checklist is filled, we can stop generating those fake component files.

 - [x] Autocomplete Quasar components
 - [x] Autocomplete props
 - [x] Autocomplete events
 - [x] Type based autocomplete for enum types (this was kinda hacked in `ide-helper` by completing the whole prop with argument, but nevertheless it is useful)
    - This is stuff like `align="justify"`, `anchor` + `self` on popovers and other props that only have finite set of predefined values. IDEA should autocomplete them inside the attribute.
    - JetBrains ticket for this feature: https://youtrack.jetbrains.com/issue/WEB-42445 (**Go Upvote It!** 😉)
    - Also related issue: https://youtrack.jetbrains.com/issue/WEB-46231 (**Go Upvote it too!** 😉)

 - [x] Go-To declaration (`ctrl-b`) - does nothing if you don't use ide-helper, otherwise it goes to fake declaration, ideally it should go to typedef in `index.d.ts`
     - JetBrains ticket: https://youtrack.jetbrains.com/issue/WEB-46768 (~~**Go Upvote that one too!**~~ 😉) **Fixed**

 - [x] Quick Doc (`ctrl-q`) 
      - this kind of stopped working recently anyway, probably because those two system clash. But in older idea versions, `ide-helper` will peovide quick doc for quasar components.

**Comment by panstromek** [comment]
Looks like webstorm started supporting enum attributes autocomplete

![image](https://user-images.githubusercontent.com/25121817/168890094-5bfa9658-4241-4d5e-a472-15e4dfa96651.png)

![image](https://user-images.githubusercontent.com/25121817/168890157-91783192-0658-43cf-ad0d-41b443d72b8d.png)

So the last remaining issue is fixed.
